export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Automovil</title>
  <base href="https://github.com/Kevin23221/Pagina-turismo.git">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.background[_ngcontent-ng-c3177019257]{background-color:#faebd7}</style><style ng-app-id="ng">.navbar[_ngcontent-ng-c2293847295]{background-color:#212529!important}.navbar-brand[_ngcontent-ng-c2293847295]{color:#f8f9fa!important;font-weight:500;text-transform:uppercase}.navbar-brand[_ngcontent-ng-c2293847295]:hover{color:#0d6efd!important}.nav-link[_ngcontent-ng-c2293847295]{color:#bbb!important;transition:color .3s ease}.nav-link[_ngcontent-ng-c2293847295]:hover, .nav-link.active[_ngcontent-ng-c2293847295]{color:#fff!important}</style><style ng-app-id="ng">.footer[_ngcontent-ng-c161835865]{position:relative}.footer-copy[_ngcontent-ng-c161835865]{background-color:#212529;color:#f8f9fa;text-align:center;padding:1rem;border-top:1px solid rgba(255,255,255,.815)}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="20.3.6" _nghost-ng-c3177019257 ngh="1" ng-server-context="ssg"><app-header _ngcontent-ng-c3177019257 _nghost-ng-c2293847295 ngh="0"><nav _ngcontent-ng-c2293847295 class="navbar navbar-expand-lg bg-body-primary"><div _ngcontent-ng-c2293847295 class="container-fluid"><a _ngcontent-ng-c2293847295 class="navbar-brand" href="https://github.com/Kevin23221/Pagina-turismo.git/home" jsaction="click:;">Inicio</a><button _ngcontent-ng-c2293847295 type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span _ngcontent-ng-c2293847295 class="navbar-toggler-icon"></span></button><div _ngcontent-ng-c2293847295 id="navbarNavDropdown" class="collapse navbar-collapse"><ul _ngcontent-ng-c2293847295 class="navbar-nav"><li _ngcontent-ng-c2293847295 class="nav-item"><a _ngcontent-ng-c2293847295 class="nav-link" href="https://github.com/Kevin23221/Pagina-turismo.git/producto" jsaction="click:;">Productos</a></li><li _ngcontent-ng-c2293847295 class="nav-item"><a _ngcontent-ng-c2293847295 class="nav-link" href="https://github.com/Kevin23221/Pagina-turismo.git/nosotros" jsaction="click:;">Sobre Nosotros</a></li><li _ngcontent-ng-c2293847295 class="nav-item"><a _ngcontent-ng-c2293847295 class="nav-link" href="https://github.com/Kevin23221/Pagina-turismo.git/contacto" jsaction="click:;">Contacto</a></li></ul></div></div></nav></app-header><main _ngcontent-ng-c3177019257><router-outlet _ngcontent-ng-c3177019257></router-outlet><app-products ngh="0"><p>products works!</p></app-products><!----></main><app-footer _ngcontent-ng-c3177019257 _nghost-ng-c161835865 ngh="0"><div _ngcontent-ng-c161835865 class="footer-copy"><h3 _ngcontent-ng-c161835865>© 2025 EMPRESA S.A.S Todos los derechos reservados.</h3></div></app-footer></app-root>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
<script src="polyfills-5CFQRCPP.js" type="module"></script><script src="main-N2LEQTLD.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"2":[{"i":"c4131455671","r":1}]}}]}</script></body></html>`;